# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /projects/perso/raytracer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /projects/perso/raytracer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /projects/perso/raytracer/CMakeFiles /projects/perso/raytracer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /projects/perso/raytracer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named raycaster.out

# Build rule for target.
raycaster.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raycaster.out
.PHONY : raycaster.out

# fast build rule for target.
raycaster.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raycaster.out.dir/build.make CMakeFiles/raycaster.out.dir/build
.PHONY : raycaster.out/fast

src/cast_ray.o: src/cast_ray.c.o
.PHONY : src/cast_ray.o

# target to build an object file
src/cast_ray.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raycaster.out.dir/build.make CMakeFiles/raycaster.out.dir/src/cast_ray.c.o
.PHONY : src/cast_ray.c.o

src/cast_ray.i: src/cast_ray.c.i
.PHONY : src/cast_ray.i

# target to preprocess a source file
src/cast_ray.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raycaster.out.dir/build.make CMakeFiles/raycaster.out.dir/src/cast_ray.c.i
.PHONY : src/cast_ray.c.i

src/cast_ray.s: src/cast_ray.c.s
.PHONY : src/cast_ray.s

# target to generate assembly for a file
src/cast_ray.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raycaster.out.dir/build.make CMakeFiles/raycaster.out.dir/src/cast_ray.c.s
.PHONY : src/cast_ray.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raycaster.out.dir/build.make CMakeFiles/raycaster.out.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raycaster.out.dir/build.make CMakeFiles/raycaster.out.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raycaster.out.dir/build.make CMakeFiles/raycaster.out.dir/src/main.c.s
.PHONY : src/main.c.s

src/map.o: src/map.c.o
.PHONY : src/map.o

# target to build an object file
src/map.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raycaster.out.dir/build.make CMakeFiles/raycaster.out.dir/src/map.c.o
.PHONY : src/map.c.o

src/map.i: src/map.c.i
.PHONY : src/map.i

# target to preprocess a source file
src/map.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raycaster.out.dir/build.make CMakeFiles/raycaster.out.dir/src/map.c.i
.PHONY : src/map.c.i

src/map.s: src/map.c.s
.PHONY : src/map.s

# target to generate assembly for a file
src/map.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raycaster.out.dir/build.make CMakeFiles/raycaster.out.dir/src/map.c.s
.PHONY : src/map.c.s

src/random.o: src/random.c.o
.PHONY : src/random.o

# target to build an object file
src/random.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raycaster.out.dir/build.make CMakeFiles/raycaster.out.dir/src/random.c.o
.PHONY : src/random.c.o

src/random.i: src/random.c.i
.PHONY : src/random.i

# target to preprocess a source file
src/random.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raycaster.out.dir/build.make CMakeFiles/raycaster.out.dir/src/random.c.i
.PHONY : src/random.c.i

src/random.s: src/random.c.s
.PHONY : src/random.s

# target to generate assembly for a file
src/random.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raycaster.out.dir/build.make CMakeFiles/raycaster.out.dir/src/random.c.s
.PHONY : src/random.c.s

src/render.o: src/render.c.o
.PHONY : src/render.o

# target to build an object file
src/render.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raycaster.out.dir/build.make CMakeFiles/raycaster.out.dir/src/render.c.o
.PHONY : src/render.c.o

src/render.i: src/render.c.i
.PHONY : src/render.i

# target to preprocess a source file
src/render.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raycaster.out.dir/build.make CMakeFiles/raycaster.out.dir/src/render.c.i
.PHONY : src/render.c.i

src/render.s: src/render.c.s
.PHONY : src/render.s

# target to generate assembly for a file
src/render.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raycaster.out.dir/build.make CMakeFiles/raycaster.out.dir/src/render.c.s
.PHONY : src/render.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... raycaster.out"
	@echo "... src/cast_ray.o"
	@echo "... src/cast_ray.i"
	@echo "... src/cast_ray.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/map.o"
	@echo "... src/map.i"
	@echo "... src/map.s"
	@echo "... src/random.o"
	@echo "... src/random.i"
	@echo "... src/random.s"
	@echo "... src/render.o"
	@echo "... src/render.i"
	@echo "... src/render.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

